06 window (import tkinter as tk)-v2
 By inputting tinker as TK and not as a (*) I am being more specific with my code and thus will make less errors when other modules come into play
Error: Toplevel() is not defined